### PR TITLE
Catch PHP Parser error and rethrow it with file information

### LINKED ISSUE #272: Catch parser error and rethrow with file information
Whenever a PHP parse error occurs, only the parse error is shown, without information about the conflicting file.

```
  [PhpParser\Error]
  Syntax error, unexpected T_MATCH on line 26
```

If I'm correct, it should be pretty trivial to catch this exception in the `ASTLocator`, and rethrow it with a own message that does include the actual file path.

https://github.com/maglnet/ComposerRequireChecker/blob/79c852fda6cffe089cb49e435570a8bbd43091b3/src/ComposerRequireChecker/ASTLocator/LocateASTFromFiles.php#L40

### PR DESCRIPTION
**Pull request by bobvandevijver**
Should fix #272.

This change ensures the Parser error is catched and its message is prepended with the file path of the file currently being parsed.

### CODE REVIEW

File: src/ComposerRequireChecker/Exception/FileParseFailed.php [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+namespace ComposerRequireChecker\Exception;
+
+use RuntimeException;
+use Throwable;
+
+class FileParseFailed extends RuntimeException
+{
+  public function __construct(string $file, Throwable $previous = NULL)
+  {
+    parent::__construct($file . ': ' . $previous->getMessage(), 0, $previous);
```
Comment (Ocramius) [inline src/ComposerRequireChecker/Exception/FileParseFailed.php]: This error message should also state that the parsing failed.

For example, one of the original exceptions reported: `Parsing the file [%s] resulted in an error.` (much more descriptive).

Can we perhaps add some prefixing wording to the message here?

**Review by Ocramius — COMMENTED** [review]
Some minor adjustments needed to CS, as well as improvements around the exception message.

File: src/ComposerRequireChecker/Exception/FileParseFailed.php (hunk 1 above)
Comment (bobvandevijver) [reply src/ComposerRequireChecker/Exception/FileParseFailed.php]: How about `sprintf('FileParseFailed: Parsing the file [%s] resulted in an error: %s', $file, $previous->getMessage());`?

Comment (bobvandevijver) [reply src/ComposerRequireChecker/Exception/FileParseFailed.php]: I do believe the prefix might be redundant though, as the exception class is also printed when run in the console

Comment (DanielBadura) [reply src/ComposerRequireChecker/Exception/FileParseFailed.php]: I think `Parsing the file [%s] resulted in an error: %s` should be enough 👍

Comment (Ocramius) [reply src/ComposerRequireChecker/Exception/FileParseFailed.php]: The suggested improvement works, although `FileParseFailed:` in front of it is indeed not needed :+1:

Comment (bobvandevijver) [reply src/ComposerRequireChecker/Exception/FileParseFailed.php]: Done! 👍🏻

**Comment by Ocramius** [comment]
One last adjustment is to add `use function sprintf` - can you please `./vendor/bin/phpcbf` on that file?

**Review by Ocramius — APPROVED** [review]
Fabulous, thanks!
